version: '3.9'

services:
  web:
    image: api:1.0.0
    container_name: api_web
    command: "./entrypoint.sh ${MODE}"
    volumes:
    - ./:/app
    env_file:
    - app.env
    depends_on:
      db:
        condition: service_healthy
    expose:
      - 8000
    networks:
    - api_net

  db:
    image: postgres:14-bullseye
    environment:
    - POSTGRES_USER=admin
    - POSTGRES_PASSWORD=admin
    - POSTGRES_DB=db_api
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
    - api_net

  nginx:
    image: target_nginx:1.0.0
    depends_on:
      - web
    ports:
      - 80:80
    networks:
    - api_net

networks:
  api_net: